### ISSUE TITLE
TS Support

### ISSUE THREAD

**Issue by alhassanv** [raxraj/simple-express-snippets#2]
Could you create some snippets that have ts support (such as the import or export default)

**Comment by raxraj** [comment]
Hey @alhassanv, I'm really sorry for this delay in response, the notification got hidden by mistake.

I can do that, can you elaborate so that I can see if we need a separate snippet for same.

**Comment by alhassanv** [comment]
> > Hey @alhassanv, I'm really sorry for this delay in response, the notification got hidden by mistake.
> I can do that, can you elaborate so that I can see if we need a separate snippet for same.

Well I guess it would be import statements instead of require.

**Comment by raxraj** [comment]
Oh, okay!!! 
Silly me. Got it.

**Comment by raxraj** [comment]
@alhassanv, TypeScript support added.
